server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: n1JRPNNvTdBaLsd0p2hL3sIQSKfeUt0d
            client-secret: dyZ9PW1in2KvyoP5wHRIR_KkbEhum-WiZCSeyxahedhIHCfzn0OUA2EAL2RuBnwf
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-ihmgw4u7qj5p1r3o.us.auth0.com/
  datasource:
    driver-class-name: org.postgresql.Driver
    password: sifraZaBazu
    url: jdbc:postgresql://localhost:5432/auth0
    username: bk53409
  jpa:
    hibernate:
      ddl-auto: create